pixijs/pixi-react

src/reconciler/hostconfig.js, src/utils/props.js, test/reconciler.test.js
Only commit updates in the render tree that are actually changed.
See also [ReactDOM Reconciler](https://github.com/facebook/react/blob/97e2911/packages/react-dom/src/client/ReactDOMFiberComponent.js#L546)
`prepareUpdate` now returns the props that needs to update. If there's nothing to update, it just returns null.
=> Implement reconciler `prepareUpdate`

src/components/Graphics.js, src/components/Mesh.js, src/components/NineSlicePlane.js, src/components/Rope.js, src/components/Sprite.js, src/components/TilingSprite.js, test/element.spec.js
Sugar syntactic props for built-in PIXI components gets update now as well.
Fix #9 
For example:
```js
class Image extends React.Component {
state = { image: 'image.png' }
render() {
return (
<Sprite image={this.state.image} 
onClick={() => this.setState({ image: 'new-image.png' })} />
)
} 
}
```
and
```js
class Image extends React.Component {
state = { count: 1 }
render() {
return (
<Graphics draw={this.draw} 
onClick={() => this.setState({ count }) => ({ count: count + 1 })} />
)
} 
draw = (g) => {
g.beginFill(0xcc0000)
let count = this.state.count
while(count--) {
g.drawRect(count * 100, 0, 50, 50)
}
g.endFill()
}
}
```
=> Apply props for built in PIXI components, see #9

index.d.ts, package.json, yarn.lock
First of all this pull request adds windows compilation support thanks to cross-env (dev dependency)
Also I fixed more typing issues, the only new thing is that in order to get proper typings PixiComponent has to be used like this in TS:
```
interface CircleProps { radius: number; }
const Circle = PixiComponent<CircleProps, PIXI.Graphics>(...)
```
The good thing is that now lifecycle methods are properly typed with the given Props interface, get the proper PIXI display object type and also when such component is used inside JSX the properties are properly validated.
PS: withPixiApp type as a decorator is still kind of broken, but it works properly as a function (this is, the wrapped class can accept a mandatory app prop and it won't be asked when using the wrapping element)
Also, changes …
=> windows compilation + better types

index.d.ts
With this pitch, you can use a factory function as 1st param for render function.
```typescript
const SuperText = t => <ReactPixi.Text text={'Super ' + t} />
render(
SuperText, // will work
app.stage
)
```
=> fix typings in render()

README.md, README.mdx
- componenDidMount -> componentDidMount
- Used ES6 arrow function, since it doesn't create a new context. Therefore, this.setState can be used without binding `this` inside class constructor
componenDidMount was missing the `t`. Also doing the classic copy-pasta 🍝 react would crash calling `this.setState of undefined`. Therefore I've replaced the function using the ES6 arrow function.
=> 🐞 Fixed wrong lifecycle method name

src/helpers/index.js
I made profile on webos and the javascript engine getting confused about that function and trying to optimize that function over and over again.
Found this while doing CPU profiling on Webos.
Hope you don't mind some optimization PRs. Trying to run 60 fps on Smart TV is impossible... 😄
I get this warning about optimize. Try/catch can be problems for javascript engines and some other things. I found this on stackoverflow.
https://stackoverflow.com/questions/22509262/what-do-the-not-optimized-warnings-in-the-chrome-profiler-mean
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers
> **Workarounds**
> 
> Some of these statements cannot be avoided in production code such as try-finally and try-catch. To use such statements with minimal impact, they must be isolated to a minimal …
=> Optimzed isFunction

README.md
It seems that `renderOnComponentChange` is an alternative to `raf=true`, and ignored if we render via `requestAnimationFrame`. This was quite confusingly put in the README, and I tried to make it a little bit clearer.
=> Clarify renderOnComponentChange documentation.

src/reconciler/hostconfig.js, test/reconciler.test.js
Implements `hideInstance` and `unhideInstance` methods for the reconciler so that React Suspense works.
I'm new to both PIXI and the React reconciler, but I referenced how [ReactDOM](https://github.com/facebook/react/blob/796c67a25f980f1bcf9507b9f7d02131b8a2b552/packages/react-dom/src/client/ReactDOMHostConfig.js#L588) implements those methods. I assumed `instance.visible` would be the appropriate property to toggle for a PIXI object, but if there's a better approach please let me know.
=> Support React Suspense

src/stage/index.js, test/stage.spec.js
Currently, the `PIXI.Application` instance always uses `this._canvas` as `view`, which is only defined if `options.view` is falsey.  So, while you can pass in something for `options.view`, that won't get hooked up to `PIXI.Application`.
=> Allow `PIXI.Application` instance to use `options.view`.

src/utils/props.js, test/props.spec.js
Do we really need to teardown and setup the same events or did I miss something? :D
All tests passed but I'm not sure that everything works :D
Like this example. The current code I think will teardown that event and then setup it again even that is the same event?
```js
const staticClick = () => console.log('STATIC');
const Something = () => (
<Sprite
interactive
click={staticClick}
/>
);
```
Also flattened that so it doesn't need to create a function scope all the time for performance reasons... Micro optimizations :D
```js
if (oldProps[evt] !== newProps[evt]) {
// ...
} else {
global.count++;
// Was here 100k times on one of my bigger scenes in just a couple of seconds in runtime.
}
```
=> Improved events handling

package.json
**In order to support PIXI5**
**fixes https://github.com/inlet/react-pixi/issues/98 by replacing canvas-prebuilt with canvas & forcing a newer jsdom on jest**
=> switching from canvas prebuilt to canvas & forcing newer jsdom

src/index.js
When creating a custom component (for example, Sprite2D from [pixi-projection](https://github.com/pixijs/pixi-projection)), it would be very handy to use applyDefaultProps to apply all the common DisplayObject properties, instead of manually having to apply them again.
=> Expose applyDefaultProps

src/reconciler/index.js, src/render/index.js
React DevTools needs to receive the React-DOM version instead of the react-pixi version in order to work.
Once this is updated, you can test with the following code:
Codesandbox: https://xk3d2.csb.app/
Codesandbox source: https://codesandbox.io/s/react-pixi-with-ref-example-xk3d2
This is the solution proposed after discussing it here: https://github.com/facebook/react/issues/16666
=> Change: Inject React-DOM version to React DevTools

index.d.ts
After a refactorization over ts def in [this pr](https://github.com/inlet/react-pixi/commit/d75f60d68a7ca67c14b9fab20bf2ed3ea4bc0118#diff-b52768974e6bc0faccb7d4b75b162c99), the Sprite object is not augmented with pointlike type for anchor prop of Sprite.
=> ts: missing pointlike for sprite's Anchor prop

index.d.ts
Missing closing `>` causes a syntax error.
=> Fix syntax error in index.d.ts

module.js
Parcel doesn't like the syntax for the require statement (at least when using TypeScript), and is unable to resolve the module. Changing to an if/else statement fixes the problem. This should only be needed in the module.js file, as Parcel will always use this.
=> FIx Parcel bundler support

src/hoc/withFilters.mdx
Based on other ReactPIXI's example coding style, added white space.
=> Add white space on import object

index.js
Seems like Parcel 2 can't detect the dependency when it's URL is produced dynamically.
=> Fix for Parcel 2

src/stage/Stage.mdx
First of all, thank you very much for this awesome library!
This is a tiny change that fixes the `Stage` doc page to have the correct default `height` value in the props table (from `800` to `600`).
Please let me know if you need anything else.
=> Fix `Stage` default height in docs to be correct value

index.d.ts, src/components/AnimatedSprite.js
Add types for `AnimatedSprite` and update play state respectively.
Fixes #194 and #195
=> Update AnimatedSprite play state and add types

index.d.ts
I could't use a type like `[number, number]` for `skew` of `PIXI.Sprite`.
So I fix it.
=> Apply PointLike type to skew

index.d.ts
These types of definitions are not working for JSX.
You probably intended to use union fields separately there, but if it is used for JSX props they will be mixed with parent intersections (IDK why)
=> Fix type definitions for container

index.d.ts
I've got this type error from recent update.
```
Argument of type 'FC<Container<Graphics, { draw?(graphics: Graphics): void; preventRedraw?: boolean | undefined; }>>' is not assignable to parameter of type 'ComponentType<Container<Container, {}>>'.
Type 'FunctionComponent<Container<Graphics, { draw?(graphics: Graphics): void; preventRedraw?: boolean | undefined; }>>' is not assignable to type 'FunctionComponent<Container<Container, {}>>'.
Types of parameters 'props' and 'props' are incompatible.
Type 'PropsWithChildren<Container<Container, {}>>' is not assignable to type 'PropsWithChildren<Container<Graphics, { draw?(graphics: Graphics): void; preventRedraw?: boolean | undefined; }>>'.
Type 'PropsWithChildren<Container<Container, {}>>' is not assignable to type …
```
=> Fix broken withFilters type inference

index.d.ts
This pull request modifies `_ReactPixi.PointLike` type definition to accept `{x: number, y:number}`
I wanted to pass `{x: number, y:number}` to `<TilingSprite />` 's `tilePosition` prop and `tileScale` prop as [noted in the doc](https://reactpixi.org/components/tiling-sprite), but that gave me type error.   
```
Type '{ x: number; y: number; }' is not assignable to type 'number | ObservablePoint | Point | [number, number] | [number] | undefined'.
Type '{ x: number; y: number; }' is not assignable to type 'undefined'.
```
As far as I read the source code(https://github.com/inlet/react-pixi/blob/master/src/components/TilingSprite.js#L15-L17
and https://github.com/inlet/react-pixi/blob/master/src/utils/pixi.js#L23-L26), `{x: number, y:number}` case seems like considered so I …
=> Add object type support for _ReactPixi.PointLike

index.d.ts
Removes the `preventRedraw` property because it is still present in index.d.ts.
https://github.com/inlet/react-pixi/blob/master/index.d.ts#L169
=> Remove "preventRedraw" prop from index.d.ts

src/stage/index.js
Fixes #238 
Propagate the `autoDensity` option to PIXI app so it updates the width and height + css styles when calling `app.renderer.resize`.
=> Use PIXI's built-in `autoDensity`

index.d.ts
The type of "ref" property on the class component always be a reference to an instance of a class component. But in react-pixi, it's a Pixi instance, so should set it to a function component and specify the type of ref property.
=> Fix type of "ref" property on custom component

src/reconciler/hostconfig.js, test/reconciler.test.js
Native components, I.e. `<Sprite>`, `<Graphics>`, etc (including `PixiComponent`) are handled as raw components and are internally not really React components, they return a PIXI instance back to the reconciler.
The problem is that if you have a nested component that relies on a `willUnmount` this might never be triggered. 
Thanks @femetrie for discovering this. 
Fixes #257
This PR calls `willUnmount` on every sequential child that acts as a native component.
=> Unmount sub children

src/utils/element.js, test/element.spec.js
When destroying, config is not assigned.
https://github.com/inlet/react-pixi/issues/303
=> Fix assignment of missing config object

src/stage/index.js, test/stage.spec.js
This PR prevents an error when using react-pixi with @pixi/events plugin.
#333
=> Support Federated Events API

src/components/Graphics.js, src/components/Graphics.mdx, test/__snapshots__/graphics.spec.js.snap, test/graphics.spec.js
When the same shapes are repeatedly used, the memory consumed by the browser becomes high. To optimise memory consumption, a geometry object can be passed to the Graphics object constructor. 
https://github.com/inlet/react-pixi/issues/327
=> add geometry prop to Graphics

.gitignore, src/components/NineSlicePlane.js, src/components/SimpleMesh.js, src/components/SimpleRope.js, src/components/Sprite.js, src/components/TilingSprite.js, src/reconciler/hostconfig.js, src/stage/Stage.mdx, src/stage/index.js, src/utils/element.js, src/utils/props.js, test/props.spec.js, test/reconciler.test.js
I've didn't manage to get the canvas instance from the hostconfig where events were emitted from, so I've basically done what react-three-fiber does: I store the root container in each pixi component. Not so elegant solution, but iterating through all branch of the tree to find root node seems a bit overhead. Also, I didn't add any new tests, bc I don't see any necessity.
Maybe I should leave old window.dispatchEvent for backwards compatibility? Ideally I'd hide this behind some kind of global flag, but I don't know how to do it good.
#339
=> Move update events from window to root container

package.json, yarn.lock
Because `docz` has peer dependencies set to less than React 18, I think this could cause problems with an NPM install
=> Remove docz ready for release

packages/react-pixi/src/reconciler/hostconfig.js, packages/react-pixi/test/element.spec.js
Fixes: https://github.com/pixijs/pixi-react/issues/367
* Call `willUnmount` iteratively during unmount
* Defer to PIXI to do object destruction to prevent double destroy call
* Add test for `willUnmount`/`destroy` calls
=> Fix `BitmapText` double destroy bug

package.json, packages/animated-legacy/package.json, packages/animated/package.json, packages/react-legacy/package.json, packages/react/package.json
`sideEffect: false` was added to root `package.json` by mistake, this PR moves it to each package
=> Move sideEffects false to each package

packages/docs/docusaurus.config.js, packages/docs/package.json
Bump `docs` to `v7.0.0-alpha.1` and fix the base url
=> Update docs version and fix baseUrl

packages/docs/docs/render/Render.mdx, packages/react/src/exports.js, packages/react/src/reconciler/hostconfig.js, packages/react/src/render/index.js, packages/react/test/__snapshots__/index.spec.js.snap, packages/react/test/reconciler.test.js, packages/react/test/render.spec.js
Resolves: https://github.com/pixijs/pixi-react/issues/379
## Changes
* Add `createRoot` API with backwards compatible `render` function.
* Fix/update tests
=> Add createRoot API

lerna.json, packages/animated/package.json, packages/react/package.json
The version numbers were reverted to an alpha version when I fixed the `v7.0.0` tag and release not being built from master.
I'll recreate the tag and release after merging this.
=> Fix borked versions

packages/animated/index.d.ts, packages/react/index.d.ts
Fixes: https://github.com/pixijs/pixi-react/issues/350
According to https://github.com/pixijs/pixi-react/issues/350#issuecomment-1413422066 and as per [suggestions on the Discord](https://discord.com/channels/734147990985375826/968068526566965279/1068509211052482580):
> Basically you have to replace each React.FC with something that adds children prop
> PropsWithChildren<T>  is mainly used for that right now
This should fix the TS issue with Container
=> Fix Container TS types bug

packages/animated/index.d.ts, packages/react/index.d.ts
Fix typings for Sprite with children.
For example this code:
```
<Container x={100} y={100}>
<Sprite texture={Assets.cache.get('/assets/texture.png')} scale={new Point(0.4, 0.4)}>
<Text
text="I am text as sprite's child"
style={new TextStyle({ fill: 0xffffff })}
/>
</Sprite>
</Container>
```
generates Sprite type error:
`Type '{ children: Element; texture: Texture<Resource>; scale: Point; }' is not assignable to type 'IntrinsicAttributes & Partial<Omit<Sprite, P | ReadonlyKeys<Sprite> | keyof WithSource> & WithPointLike<P>> & WithSource & InteractionEvents & { ...; }'.   Property 'children' does not exist on type 'IntrinsicAttributes & Partial<Omit<Sprite, P | ReadonlyKeys<Sprite> | keyof WithSource> & WithPointLike<P>> & WithSource & InteractionEvents & { ...; }'.`
=> Fix typings for sprite with children

packages/docs/docs/hooks/Hooks.mdx
Updates the hooks docs to describe that hooks must be wrapped by an AppProvider. This has been confusing to new users https://github.com/pixijs/pixi-react/issues/410
=> Add AppProvider usage description in hooks docs

packages/react/src/stage/index.js
Fix support for canvas renderer
Figured out that `loseContext` only exists as an extension for webgl, so no point in trying to set it for canvas.
Fixes: support for canavas renderer
=> Fix support for canvas renderer

packages/docs/docs/components/Text.mdx
VSCode API docs says `fontWeight` should be `type TextStyleFontWeight = "bold" | "normal" | "bolder" | "lighter" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900"`
Fixes:  no issue.
I didn't change code.
=> Fix typo in Text.mdx

packages/react/src/components/AnimatedSprite.js, packages/react/test/element.spec.js
Currently, updating the image attribute does not update the actual textures on the animated sprite component.  My PR fixes this by checking to see if the images are distinct from the previous iteration, and actually updating them accordingly.
Fixes: 
Will do soon, manually testing still - and looking for some feedback
=> Fixes AnimatedSprite component when images are updated

packages/react/src/reconciler/hostconfig.js
When having a conditional child for a `<Container>` within a `<Stage>` the child does not reappear once removed.
Fixes: #408 #469
=> Fix hostconfig insertBefore requesting rerender fixes #408

src/hooks/useAsset.ts
Does what it says on the tin.
Fixes: #502
=> Make `useAsset`'s `onProgress` type optional

src/helpers/insertBefore.ts
Fixes an issue where inserting a new child or reordering children could cause an uncaught exception.
=> fix: reordering children could cause errors

src/hooks/useTick.ts
`useTick` failed to fire on the first tick in server-rendered environments (such as Next.js applications) because the `useEffect` wasn't being triggered. This is fixed by switching to use `useIsomorphicLayoutEffect` instead.`
Fixes: #506
=> Fix `useTick` during initial load when using server components

package-lock.json, package.json
Updates Pixi React to the latest version of Pixi.js. This version exposes a type that's required for Pixi React to continue building.
=> Update to Pixi.js 8.2.6

src/hooks/useTick.ts
A minor thing that got missed when deploying the previous fix for #506 
Fixes: #506
=> Ensure `useTick` callback is updated when app is initialised

src/constants/PixiReactIgnoredProps.ts, src/helpers/applyProps.ts, src/helpers/createInstance.ts, src/helpers/diffProps.ts, src/helpers/gentleCloneProps.ts
Events will now be applied the first time a component is rendered.
Fixes: #520
=> Apply events on first render

src/constants/PixiReactIgnoredProps.ts, src/helpers/createInstance.ts, src/helpers/gentleCloneProps.ts
Fixes the issue where `draw` was no longer being run appropriately for `<graphics>` components.
=> Restore `draw` method being run for `<graphics>` components

README.md, src/components/Application.ts, src/typedefs/ApplicationProps.ts
Adds the `extensions` property to the `<Application>` component, which allows Pixi React to manage adding/removing extensions for the user.
This is mostly a convenience property. If the user needs to load an extension, then can just as easily use a `useEffect` to run `extensions.add(Extension)`. If they need it to be initialised before the `<Application>`, they can call `extensions.add` and only render the `<Application>` after the extensions have been added. That said... this is way easier. 😝
=> Add support for managing `extensions`

.vscode/launch.json, src/hooks/useAssets.ts, test/unit/hooks/useAssets.test.tsx
Generates a failing test for issue #531
Potential fix for #531; please modify or review as necessary.
Fixes: #531
=> fix: always attempt to resolve useAssets from cache  #531

package-lock.json, package.json, src/components/Application.tsx, src/core/createRoot.tsx, src/index.ts, test/e2e/components/Application.test.tsx, test/e2e/components/__snapshots__/Application.test.tsx.snap, test/e2e/hooks/useApplication.test.tsx, test/e2e/hooks/useTick.test.tsx
I'm using the `FiberProvider` and `useContextBridge` from [`its-fine`](https://github.com/pmndrs/its-fine) to allow React Contexts that are established outside of an `<Application>` to be available inside of the component.
Fixes: #557
=> bug: allow external context to be accessed from within `<Application>`

src/typedefs/ConstructorOptions.ts, src/typedefs/ConstructorOverrides.ts
Container, Sprite and Graphics all have constructors that union the options with Texture | GraphicsContext | undefined, these  types are not valid as props for a component, and the union was causing Omit and other utils to produce incorrect types when trying to extend the builtin types.
Excluding the unioned types from ConstructorOptions eleminates potential incorrect props and allows for Pick, Omit, etc to work as expected.
Fixes:
=> fix: Remove union types from ConstructorOptions

README.md, eslint.config.mjs, src/global.ts, src/index.ts, src/typedefs/HostConfig.ts, src/typedefs/NamespacedPixiElements.ts, src/typedefs/PixiElements.ts, src/typedefs/PrefixedPixiElements.ts, src/typedefs/UnprefixedPixiElements.ts, test/unit/typedefs/PixiElements.test.tsx
* Removes unprefixed elements by default
* Updates the README
* Update supported React versions
* Update minimum Pixi.js version in install command
* Remove deprecated APIs
* Abstract Typescript docs into their own section
* Add documentation for enabling the unprefixed elements
Fixes: #549
=> Remove unprefixed elements

src/typedefs/ApplicationProps.ts
Updates type signature of `resizeTo` on `Application` for react 19 compatability
In react 19 [useRef requires an argument](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#useref-requires-argument) and the type signature has changed slightly. It's a bit more strict by default, so the type needs to be manually widened in order to work for common use cases like the one in the docs:
```jsx
import { Application } from '@pixi/react'
import { useRef } from 'react'
const MyComponent = () => {
const parentRef = useRef<HTMLDivElement>(null) // <- returns RefObject<HTMLDivElement | null>
return (
<div ref={parentRef}>
<Application resizeTo={parentRef} /> 
{/* ^ will throw an error if we ask for RefObject<HTMLElement> - null is not assignable to element */}
</div>
)
}
```
=> fix(types): update resizeTo ref type

src/helpers/isReadOnlyProperty.ts
Addresses an issue where normal writable object properties were being incorrectly identified as read-only and not updating in `applyProps()`.
Fixes: https://github.com/pixijs/pixi-react/issues/563
=> Add 'writable' descriptor check to isReadOnlyProperty

src/core/createRoot.tsx
This is causing issues with attempting to use the package from skypack
Fixes:
=> Do not use extension on ConcurrentRoot import

package-lock.json, package.json, rollup.config.mjs
Update the Rollup config to output 3 bundles.
- `lib`: Existing standard lib
- `dist-dev`: @pixi/react bundled in development
- `dist-prod` @pixi/react bundled in production and minified
The ouput in the dist folder bundles all dependencies [its-fine, react-reconciler], while the lib remains unbundled.
Please provide feedback on structure for maintainability, may be better to flatten into more explicit outputs.
Fixes: 
Example Usage:
```html
<html>
<head>
<title>@pixi/react</title>
<style>
body,
div {
height: 100vh;
margin: 0;
display: grid;
place-items: center;
}
</style>
<script type="importmap">
{
"imports": {
"react": "https://esm.sh/react@19.0.0",
"react/jsx-runtime": "https://esm.sh/react@19.0.0/jsx-runtime.js",
"react-dom/client": "https://esm.sh/react-dom@19.0.0/client", …
```
=> Bundle @pixi/react for use without bundler

src/hooks/useTick.ts
`useTick` has missing dependencies that are detected with `eslint-plugin-react-hooks`, accept the recommended fix from the plugin.
Fixes #587
=> fix: add missing dependencies to useTick

eslint.config.mjs, package-lock.json, package.json
Adds [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) and configures `useIsomorphicLayoutEffect` as an additional hook to run exhaustive-deps on.
=> chore: config eslint-plugin-react-hooks

rollup.config.mjs
CRA and Parcel have bundle errors due to a bug in the bundle refactor.
This change restores  proper externalization of `its-fine` and `react-reconciler` in the `lib` bundle.
=> fix: externalize dependencies for packaged lib

src/components/Application.tsx, test/e2e/components/Application.test.tsx
I believe there is a bug in the `Application` component. When it's trying to initalize the `extensions` prop it should use for *of* to get the values, rather than for *in*, which uses the keys.
The following is the bug that comes back from pixi's `normalizeExtension` code when you specify an array of extensions as a prop of `Application`, note that the param `ext` has a value of `0` (the first key in the array)
ps. I agree this javascript language feature is quite stupid. [Array.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach) is much superior, imo :)
=> fix initialization of extensions
