pixijs/pixi-react

- src/stage/index.js
- test/stage.spec.js
Quick and dirty PR from github UI. Haven't done massive testing and no test included.
https://github.com/inlet/react-pixi/issues/7
> Add teardown of application in stage component

- index.d.ts
Fix for typings in TS2.8
Fixes #10
> Fixed typings for TS 2.8

- src/utils/props.js
- test/__snapshots__/props.spec.js.snap
> Fix cursor prop

- src/stage/index.js
- test/stage.spec.js
Would be good to be able to turn on/off the ticker.
Haven't tested the code but I think it would work... 😄
> Make Stage raf dynamic

- index.d.ts
> Support refs in definition file

- index.d.ts
> Update type definition to support Canvas attributes.

- index.d.ts
> Add hooks to type def

- src/helpers/index.js
- src/utils/props.js
I've improved so you don't have to create filter function while running and changed forEach to for loops. That tends to be a little bit faster. According to a lot of jsperf :)
> Optimzed applyDefaultProps

- .babelrc
- package-lock.json
- package.json
- src/helpers/index.js
- src/utils/props.js
- test/stage-context.spec.js
- test/stage.spec.js
Fix bug in `applyDefaultProps` optimization that prevent events to fire double.
> Fix double events

- src/hooks/useTick.js
- test/stage.spec.js
Added a way to disable the `useTick` and also made improvement to performance.
What do you think?
I can add test if you think this belongs...
> Added disabled to useTick

- index.d.ts
Fix typing `withPixiApp`, should fix #91
> Fix withPixiApp HOC

- src/utils/props.js
I would like to be able to control this in my app.
fixes #100
> expose 'crossorigin' property of Texture.fromImage

- README.mdx
- src/stage/Stage.mdx
Add a simple example to the landing page of docs
> Add example to docs

- README.md
- README.mdx
- Update documentation (README.md) links to documentation.
- Update the repo logo
modifications can be seen here: https://github.com/fabienjuif/react-pixi/blob/patch-1/README.md
**Related issue (if exists):** #123
> :memo: update v4 links and logo to v5

- src/components/AnimatedSprite.js
- src/components/AnimatedSprite.mdx
- src/components/AnimatedSpriteDocz.js
- src/components/index.js
- src/index.js
- src/utils/element.js
- test/__snapshots__/element.spec.js.snap
- test/__snapshots__/index.spec.js.snap
- test/element.spec.js
Added among the default component the AnimatedSprite  
> Add PIXI.AnimatedSprite support

- index.d.ts
When I was looking at this page, I discovered that SimpleMesh Types were not enough.
And I added it.
> Fix SimpleMesh types

- src/helpers/index.js
- src/hoc/index.js
- src/hoc/withFilters.js
- src/hoc/withFilters.mdx
- src/index.js
- test/__snapshots__/index.spec.js.snap
- test/hoc.spec.js
High Order component to create filter wrapper
#63
> implement filter wrapper for components

- src/components/AnimatedSprite.js
> Fix issue with bundle size

- index.d.ts
> Include reconciler interface

- index.d.ts
- src/hoc/withFilters.js
> withFilters is missing in typings.d.ts #158

- index.d.ts
Fix missing property preventRedraw in index.d.ts
Fix syntax error in index.d.ts
> Fix missing property preventRedraw in index.d.ts

- src/components/Text.js
- src/components/Text.mdx
- test/element.spec.js
Add the isSprite option to Text component in order to render texts as a textures. This has a much better performances
> Text as texture

- src/components/AnimatedSprite.js
Fix #183 
183A super simple check to make sure to only update textures when they actually change.
> Improve texture updates on AnimatedSprite

- README.md
https://github.com/inlet/react-pixi/issues/59
> add `pixi.js` in install command in README.md

- src/reconciler/hostconfig.js
Rewrote error messages for clarity. Fixes #189
> Added new error message

- index.d.ts
Two typescript fixes
- Fix type for IGraphics
- Components can have children again
> Fix ts 1.2.17

- src/hooks/useTick.js
Avoid nullreference when removing ticker
> useTick wont crash trying to remove null ticker

- src/reconciler/hostconfig.js
I spent quite some time tracking down a bug where I had a stray text node in my jsx. Maybe something like this will help people find these issues quicker.
> Provide more info in text node error

- CustomComponent.mdx
- README.md
- README.mdx
- doczrc.js
- src/stage/Stage.mdx
- Make README shorter and more readable
- Move API to site
> Update README & Docs

- src/components/AnimatedSprite.js
- src/components/Graphics.js
- src/components/NineSlicePlane.js
- src/components/SimpleMesh.js
- src/components/SimpleRope.js
- src/components/Sprite.js
- src/components/TilingSprite.js
- src/utils/pixi.js
- test/element.spec.js
Built in compoenents which have `applyProps` method have no return statement. In `hostconfig.js` in `commitUpdate` method, `applyProps` defines if render is called.
> Fix skipped return statement in custom applyProps

- CustomComponent.mdx
- index.d.ts
- src/reconciler/hostconfig.js
- test/reconciler.test.js
> Prevent auto destroy

- index.d.ts
**Description:** Expose InteractionEvent types as explained in related issue
**Related issue (if exists):** #310
> Export InteractionEvent types

- .github/workflows/doc.yml
- nx.json
- package-lock.json
- package.json
- packages/docs/docs/about.mdx
- packages/docs/docs/components/BitmapText.mdx
- packages/docs/docs/components/Container.mdx
- packages/docs/docs/components/NineSlicePlane.mdx
- packages/docs/docs/components/ParticleContainer.mdx
- packages/docs/docs/components/SimpleMesh.mdx
- packages/docs/docs/components/SimpleRope.mdx
- packages/docs/docs/components/Sprite.mdx
- packages/docs/docs/components/TilingSprite.mdx
- packages/docs/docs/fallback-to-canvas.mdx
- packages/docs/docs/stage/Stage.mdx
- packages/docs/docs/typescript.mdx
- packages/docs/docusaurus.config.js
Update github action
Fixed issue with assets not being loaded
> fix doc deployment

- .github/workflows/release.yml
Generates release notes on a new tag
> Add GH release action

- package.json
- scripts/checkReleaseBranch.mjs
Small script to prevent release on a branch that isn't master
> Add check for master branch prerelease script

- .codesandbox/ci.json
> Add codesandbox ci config

- packages/react/index.d.ts
Adding a typing for exported createRoot functionality.
Fixes: #403
> Fix createRoot typings

- packages/react/README.md
Little addition to the read me to make sure that @inlet 's efforts are correctly recognised on this project 👍
> update to the readme

- packages/docs/docs/about.mdx
- packages/react/README.md
Supersedes #492 #491 #482 #481 
- Manually specify v7 in install command
- Stage takes a `width` and `height`, not an `x` and `y`
- Updated Quick start App component to correctly default export
- Updated README to use Vite for consistency with docs
Fixes:
> Various Documentation fixes

- release.config.js
Updates the release config to use the `main` branch (renamed from `master`).
> Update branch names in release config

- package-lock.json
- package.json
- src/hooks/useAsset.ts
- src/hooks/useAssets.ts
- src/hooks/useSuspenseAssets.ts
- src/typedefs/UseAssetsResult.ts
- test/unit/hooks/useAssets.test.tsx
Update type definitions to match the types of Assets.load
Fixes: #526
> fix: ensure that useAssets does not infer type from data

- README.md
- src/index.ts
exports PixiReactElementProps for typing custom pixi components
> types: export PixiReactElementProps

- .github/workflows/handle-release-branch-push.yml
Adds support for merge queue events to our workflows.
> Support merge queues

- README.md
- src/typedefs/UseTickOptions.ts
1. Change `isEnabled` types from `true` to `boolean`
2. Add missing `isEnabled` parameter in README
> fix: update `useTick` `isEnabled` typedef and readme

- docs/docusaurus.config.ts
> docs: move docs to subdomain

- docs/docs/extend.mdx
> Tiny bit of typo in extend.mdx
